### ISSUE TITLE
handle LISTEN_FDS

### ISSUE THREAD

**Issue by hallyn** [lxc/lxcri#13]
crio will optionally send nsfds for some of the namespaces that are shared with the pod.  Use those if sent.

**Comment by mikemccracken** [comment]
revisiting this much later, I can't find in the OCI runtime spec where it says you might get nsfds.
I only see paths. 

@hallyn or @tych0 - do you guys remember where this is documented?

**Comment by tych0** [comment]
On Thu, Feb 13, 2020 at 08:09:38PM -0800, Michael McCracken wrote:
> revisiting this much later, I can't find in the OCI runtime spec where it says you might get nsfds.
> I only see paths. 
> 
> @hallyn or @tych0 - do you guys remember where this is documented?

I don't, but what's weird is that our containers/pods *do* actually
share namespaces, viz. the kill bug that we haven't really fixed. In
fact, I should write that up now :)

**Comment by r10r** [comment]
ups, the  reference from the commit was for an issue in the forked project.

> I only see paths. 

Yes I think this is not about `namespaces` but about additional file descriptors passed from the runtime.

see  https://github.com/opencontainers/runtime-spec/blob/master/runtime-linux.md

> The runtime MAY pass additional file descriptors to the application to support features such as socket activation. 

This could be implemented right here

https://github.com/drachenfels-de/lxcri/blob/9c901fb8de377af12ad95853fdaaeef152357157/runtime.go#L251

I do not know whether is used at all. Conformance tests run fine without it.
And to avoid leaking file descriptors to the container I would rather not implemented it until there is a real need for it.

**Comment by r10r** [comment]
The piece that was missing is that the OCI commandline interface  defines the environment variable `LISTEN_FDS` for that: 

>  *`LISTEN_FDS`:* The number of file descriptors passed.
>       For example, `LISTEN_FDS=2` would mean that the runtime MUST pass file descriptors 3 and 4 to the container process (in addition to the standard streams) to support [socket activation][systemd-listen-fds].

see https://github.com/opencontainers/runtime-tools/blame/master/docs/command-line-interface.md#L78

**Comment by hallyn** [comment]
@r10r  fwiw that would not be what I had meant.  But given that apparently I was wrong, hijacking this issue for a real issue is fine :)

**Comment by r10r** [comment]
@hallyn I didn't mean to be rude - i just felt the urge to do it. I'm glad you confirmed it 👍

**Comment by brauner** [comment]
Can this be closed? :)

**Comment by r10r** [comment]
Yes it can. I'll do that once I've updated lxcri.
