### ISSUE TITLE
handle linux resources stanza

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxcri#22]
https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#example-3

this includes device access and cgroup settings such as `cpu.shares`

**Comment by r10r** [comment]
@mikemccracken can we close this in favour of #33 ?

Stubs for implementing cgroup2 resource limits are already in place. But only a few limits already set. https://github.com/lxc/lxcri/blob/cbc79e17a3ee7bfe321b439ed22e627803488772/cgroup.go#L69

**Comment by mikemccracken** [comment]
Sure, yeah
