### ISSUE TITLE
some question about lxcri

### ISSUE THREAD

**Issue by Hormashi** [lxc/lxcri#58]
Hello
I have some question about lxcri:
1. Is it support both lxc and lxd?
2. Is it better than [lxe](https://github.com/automaticserver/lxe)?
3. Have you any community for lxcri?

**Comment by r10r** [comment]
Hello @Hormashi, thanks for your interest in lxcri.

1. No, lxcri uses lxc (liblxc)
2. I don't know. But lxcri is a OCI compliant container runtime that can be used with cri-o similar to runc. 
You can use lxcri alongside other OCI runtimes (runc, crun ...) within cri-o  if you want to.
lxe is a CRI shim for lxd, so you don't need cri-o. 
So it depends whether you want to run kubernetes on an existing lxd cluster or not.
3. There is no community separate from the lxc community, but lxcri is part of the lxc organisation.
